language: node_js
warnings_are_errors: false
node_js:
  - lts/*
cache:
  directories:
    - node_modules
install: skip
script:
  - npm run test
after_success:
  - git config --global user.name "${U_NAME}"
  - git config --global user.email "${U_EMAIL}"
  - git clone "https://${GH_TOKEN}@${GH_REF}"
  - if [! -d "${GH_DIR}"]; then
  - mkdir "${GH_DIR}"
  - fi
  - cp -rf blocks/* "${GH_DIR}"
  - cd ./yolkworks-preview
  - git add .
  - git commit -m 'travis-ci auto trigger yolkworks-preview'
  - git status
  - git remote -v
  - git push origin "${P_BRANCH}"
branches:
  only:
    - master